spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    filter-order: 1
    url: .*
    rate-limits:
    - cache-key: '@securityService.apiKey()'
      bandwidths:
      - capacity: 5
        time: 1
        unit: Minutes